name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  glassmorphism: ^3.0.0
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  lottie: ^2.4.0
  smooth_page_indicator: ^1.1.0
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11

flutter_native_splash:
  android: true
  color: "#FFFFFF"
  image: "assets/appicon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:
  - assets/

flutter:
  uses-material-design: true
